export const data = JSON.parse("{\"key\":\"v-74bc627b\",\"path\":\"/about/\",\"title\":\"关于\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"关于\",\"date\":\"2020-07-28T11:27:08.000Z\",\"draft\":false,\"sidebar\":false,\"breadcrumb\":false,\"pageInfo\":false,\"contributors\":false,\"editLink\":false,\"lastUpdated\":false,\"prev\":false,\"next\":false,\"comment\":false,\"description\":\"2020 年毕业后为了“混口饭吃”便开启了运维开发的升级之路，在升级的过程中，我发现我很喜欢“折腾”🤔。 结果折腾了半天遇到了一些“相当大的问题”，一是时间长了脑子记不住下次用到的时候还得折腾一遍，效率太低；二是和朋友吹水时不便于我出示证明我实力的关键证据😂，三是“有点东西”不是好找点工作吗🙈？ 说到底，那你最终还是得卷起来啊！ 为捋清脑袋中无序的片段，于是我开始在此进行记录📝。 不要在该奋斗的年纪选择安逸，在这记录了我成长的脚步。 如果你喜欢，或者想与我交流，可以点击上方头像下的图标。 再次感谢你的关注与阅读。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/about/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Ryan's Notebook\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"关于\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"2020 年毕业后为了“混口饭吃”便开启了运维开发的升级之路，在升级的过程中，我发现我很喜欢“折腾”🤔。 结果折腾了半天遇到了一些“相当大的问题”，一是时间长了脑子记不住下次用到的时候还得折腾一遍，效率太低；二是和朋友吹水时不便于我出示证明我实力的关键证据😂，三是“有点东西”不是好找点工作吗🙈？ 说到底，那你最终还是得卷起来啊！ 为捋清脑袋中无序的片段，于是我开始在此进行记录📝。 不要在该奋斗的年纪选择安逸，在这记录了我成长的脚步。 如果你喜欢，或者想与我交流，可以点击上方头像下的图标。 再次感谢你的关注与阅读。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2023-02-24T08:36:50.000Z\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-07-28T11:27:08.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2023-02-24T08:36:50.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"关于\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-07-28T11:27:08.000Z\\\",\\\"dateModified\\\":\\\"2023-02-24T08:36:50.000Z\\\",\\\"author\\\":[]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.85,\"words\":254},\"filePathRelative\":\"about/README.md\",\"localizedDate\":\"2020年7月28日\",\"excerpt\":\"<br>\\n<p><strong>2020</strong> 年毕业后为了“混口饭吃”便开启了运维开发的升级之路，在升级的过程中，我发现我很喜欢“<strong>折腾</strong>”🤔。</p>\\n<p>结果折腾了半天遇到了一些“相当大的问题”，一是时间长了脑子记不住下次用到的时候还得折腾一遍，效率太低；二是和朋友吹水时不便于我出示证明我实力的关键证据😂，三是“有点东西”不是好找点工作吗🙈？</p>\\n<p><strong>说到底，那你最终还是得卷起来啊！</strong></p>\\n<br>\\n<p>为捋清脑袋中无序的片段，于是我开始在此进行记录📝。</p>\\n<br>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">不要在该奋斗的年纪选择安逸，在这记录了我成长的脚步。</p>\\n<p>如果你喜欢，或者想与我交流，可以点击上方头像下的图标。</p>\\n<p>再次感谢你的关注与阅读。</p>\\n</div>\",\"autoDesc\":true,\"git\":{\"createdTime\":1677227810000,\"updatedTime\":1677227810000,\"contributors\":[{\"name\":\"Ryanxin\",\"email\":\"ryanxin@xx9z@outlook.com\",\"commits\":1}]}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
