export const data = JSON.parse("{\"key\":\"v-658dc8ca\",\"path\":\"/k8s/10.%20%E5%AE%9E%E6%88%98%E6%A1%88%E4%BE%8B-WordPress.html\",\"title\":\"\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"https://cn.wordpress.org/download/releases/ (https://cn.wordpress.org/download/releases/) 1.准备PHP镜像 官方PHP镜像 自制PHP镜像 编写Dockerfile ```bash [PHP] ;;;;;;;;;;;;;;;;;;; ; About php.in...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/k8s/10.%20%E5%AE%9E%E6%88%98%E6%A1%88%E4%BE%8B-WordPress.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"知识库\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"https://cn.wordpress.org/download/releases/ (https://cn.wordpress.org/download/releases/) 1.准备PHP镜像 官方PHP镜像 自制PHP镜像 编写Dockerfile ```bash [PHP] ;;;;;;;;;;;;;;;;;;; ; About php.in...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1.准备PHP镜像\",\"slug\":\"_1-准备php镜像\",\"link\":\"#_1-准备php镜像\",\"children\":[{\"level\":3,\"title\":\"官方PHP镜像\",\"slug\":\"官方php镜像\",\"link\":\"#官方php镜像\",\"children\":[]},{\"level\":3,\"title\":\"自制PHP镜像\",\"slug\":\"自制php镜像\",\"link\":\"#自制php镜像\",\"children\":[]},{\"level\":3,\"title\":\"\",\"slug\":\"-1\",\"link\":\"#-1\",\"children\":[]}]},{\"level\":2,\"title\":\"2. 准备nginx镜像\",\"slug\":\"_2-准备nginx镜像\",\"link\":\"#_2-准备nginx镜像\",\"children\":[{\"level\":3,\"title\":\"编写 Dockefile\",\"slug\":\"编写-dockefile\",\"link\":\"#编写-dockefile\",\"children\":[]},{\"level\":3,\"title\":\"打包镜像\",\"slug\":\"打包镜像-1\",\"link\":\"#打包镜像-1\",\"children\":[]}]},{\"level\":2,\"title\":\"3. 创建PV/PVC\",\"slug\":\"_3-创建pv-pvc\",\"link\":\"#_3-创建pv-pvc\",\"children\":[{\"level\":3,\"title\":\"NFS服务器\",\"slug\":\"nfs服务器\",\"link\":\"#nfs服务器\",\"children\":[]},{\"level\":3,\"title\":\"pv/pvc yaml文件\",\"slug\":\"pv-pvc-yaml文件\",\"link\":\"#pv-pvc-yaml文件\",\"children\":[]},{\"level\":3,\"title\":\"查看pv状态\",\"slug\":\"查看pv状态\",\"link\":\"#查看pv状态\",\"children\":[]}]},{\"level\":2,\"title\":\"部署wordpress\",\"slug\":\"部署wordpress\",\"link\":\"#部署wordpress\",\"children\":[{\"level\":3,\"title\":\"查看Pod状态\",\"slug\":\"查看pod状态\",\"link\":\"#查看pod状态\",\"children\":[]}]},{\"level\":2,\"title\":\"初始化安装配置wordpress\",\"slug\":\"初始化安装配置wordpress\",\"link\":\"#初始化安装配置wordpress\",\"children\":[{\"level\":3,\"title\":\"初始化数据库\",\"slug\":\"初始化数据库\",\"link\":\"#初始化数据库\",\"children\":[]},{\"level\":3,\"title\":\"测试上传图片\",\"slug\":\"测试上传图片\",\"link\":\"#测试上传图片\",\"children\":[]}]}],\"readingTime\":{\"minutes\":50.21,\"words\":15062},\"filePathRelative\":\"k8s/10. 实战案例-WordPress.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
