export const data = JSON.parse("{\"key\":\"v-c687dcc8\",\"path\":\"/k8s/2.%20etcd%20%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E3%80%81%E6%95%B0%E6%8D%AE%E5%A4%87%E4%BB%BD%E4%B8%8E%E6%81%A2%E5%A4%8D.html\",\"title\":\"\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"etcd是CoreOS团队于2013年6月发起的开源项目，它的目标是构建一个高可用的分 布式键值(key-value)数据库。etcd内部采用raft协议作为-致性算法，etcd基于Go语言实现。 官方网站：https://etcd.io (https://etcd.io)github地址: https://github.com/etcd-io/etc...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/k8s/2.%20etcd%20%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E3%80%81%E6%95%B0%E6%8D%AE%E5%A4%87%E4%BB%BD%E4%B8%8E%E6%81%A2%E5%A4%8D.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"知识库\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"etcd是CoreOS团队于2013年6月发起的开源项目，它的目标是构建一个高可用的分 布式键值(key-value)数据库。etcd内部采用raft协议作为-致性算法，etcd基于Go语言实现。 官方网站：https://etcd.io (https://etcd.io)github地址: https://github.com/etcd-io/etc...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":3,\"title\":\"验证当前etcd所有成员状态\",\"slug\":\"验证当前etcd所有成员状态\",\"link\":\"#验证当前etcd所有成员状态\",\"children\":[]},{\"level\":2,\"title\":\"查看etcd数据信息\",\"slug\":\"查看etcd数据信息\",\"link\":\"#查看etcd数据信息\",\"children\":[{\"level\":3,\"title\":\"1.查看所有key\",\"slug\":\"_1-查看所有key\",\"link\":\"#_1-查看所有key\",\"children\":[]},{\"level\":3,\"title\":\"2.查看指定key\",\"slug\":\"_2-查看指定key\",\"link\":\"#_2-查看指定key\",\"children\":[]},{\"level\":3,\"title\":\"3.查看所有calico的数据\",\"slug\":\"_3-查看所有calico的数据\",\"link\":\"#_3-查看所有calico的数据\",\"children\":[]},{\"level\":3,\"title\":\"etcd增删改查数据\",\"slug\":\"etcd增删改查数据\",\"link\":\"#etcd增删改查数据\",\"children\":[]}]},{\"level\":2,\"title\":\"etcd数据watch机制\",\"slug\":\"etcd数据watch机制\",\"link\":\"#etcd数据watch机制\",\"children\":[]},{\"level\":2,\"title\":\"etcd 数据手动备份与恢复\",\"slug\":\"etcd-数据手动备份与恢复\",\"link\":\"#etcd-数据手动备份与恢复\",\"children\":[{\"level\":3,\"title\":\"\",\"slug\":\"\",\"link\":\"#\",\"children\":[]},{\"level\":3,\"title\":\"使用kubeasz 备份与恢复数据\",\"slug\":\"使用kubeasz-备份与恢复数据\",\"link\":\"#使用kubeasz-备份与恢复数据\",\"children\":[]},{\"level\":3,\"title\":\"ETCD 数据恢复流程\",\"slug\":\"etcd-数据恢复流程\",\"link\":\"#etcd-数据恢复流程\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.83,\"words\":1749},\"filePathRelative\":\"k8s/2. etcd 客户端使用、数据备份与恢复.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
