export const data = JSON.parse("{\"key\":\"v-c3628ba0\",\"path\":\"/k8s/8.%20%E5%AE%9E%E6%88%98%E6%A1%88%E4%BE%8B-%E5%9F%BA%E4%BA%8EStatefulSet%20MySQL%20%E4%B8%BB%E4%BB%8E%E6%9E%B6%E6%9E%84.html\",\"title\":\"\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"https://kubernetes.io/zh-cn/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/ (https://kubernetes.io/zh-cn/docs/tutorials/stateful-application/mysql-wordpre...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/k8s/8.%20%E5%AE%9E%E6%88%98%E6%A1%88%E4%BE%8B-%E5%9F%BA%E4%BA%8EStatefulSet%20MySQL%20%E4%B8%BB%E4%BB%8E%E6%9E%B6%E6%9E%84.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"知识库\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"https://kubernetes.io/zh-cn/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/ (https://kubernetes.io/zh-cn/docs/tutorials/stateful-application/mysql-wordpre...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"StatefulSet 的组成部分\",\"slug\":\"statefulset-的组成部分\",\"link\":\"#statefulset-的组成部分\",\"children\":[]},{\"level\":2,\"title\":\"\",\"slug\":\"\",\"link\":\"#\",\"children\":[]},{\"level\":2,\"title\":\"镜像准备\",\"slug\":\"镜像准备\",\"link\":\"#镜像准备\",\"children\":[]},{\"level\":2,\"title\":\"创建PV\",\"slug\":\"创建pv\",\"link\":\"#创建pv\",\"children\":[{\"level\":3,\"title\":\"创建nfs共享存储目录\",\"slug\":\"创建nfs共享存储目录\",\"link\":\"#创建nfs共享存储目录\",\"children\":[]},{\"level\":3,\"title\":\"创建PV yaml文件\",\"slug\":\"创建pv-yaml文件\",\"link\":\"#创建pv-yaml文件\",\"children\":[]}]},{\"level\":2,\"title\":\"创建 ConfigMap\",\"slug\":\"创建-configmap\",\"link\":\"#创建-configmap\",\"children\":[]},{\"level\":2,\"title\":\"创建 无头服务\",\"slug\":\"创建-无头服务\",\"link\":\"#创建-无头服务\",\"children\":[]},{\"level\":2,\"title\":\"创建 StatefulSet\",\"slug\":\"创建-statefulset\",\"link\":\"#创建-statefulset\",\"children\":[{\"level\":3,\"title\":\"运⾏mysql服务\",\"slug\":\"运行mysql服务\",\"link\":\"#运行mysql服务\",\"children\":[]},{\"level\":3,\"title\":\"验证MySQL主从同步是否正常\",\"slug\":\"验证mysql主从同步是否正常\",\"link\":\"#验证mysql主从同步是否正常\",\"children\":[]}]}],\"readingTime\":{\"minutes\":7.62,\"words\":2286},\"filePathRelative\":\"k8s/8. 实战案例-基于StatefulSet MySQL 主从架构.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
