export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"濼鑫的知识库\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"icon\":\"home\",\"title\":\"濼鑫的知识库\",\"heroImage\":\"/logo2.png\",\"heroText\":\"濼鑫的知识库\",\"tagline\":\"不要在该奋斗的年纪选择安逸，在这记录了我成长的脚步.\",\"actions\":[{\"text\":\"开始💡\",\"link\":\"/k8s/\",\"type\":\"primary\"},{\"text\":\"About\",\"link\":\"/about/\"}],\"features\":[{\"title\":\"Kubernetes\",\"icon\":\"support\",\"details\":\"Kubernetes是Google开源的一个容器编排引擎，它支持自动化部署、大规模可伸缩、应用容器化管理。\",\"link\":\"/k8s/log/\"},{\"title\":\"Redis\",\"icon\":\"layout\",\"details\":\"一个开源的可基于内存也可持久化的Key-Value数据库。\",\"link\":\"/statuspage/\"},{\"title\":\"Ceph\",\"icon\":\"more\",\"details\":\"Ceph是一种为优秀的性能、可靠性和可扩展性而设计的统一的、分布式文件系统。\",\"link\":\"/statuspage/\"},{\"title\":\"ELASTIC STACK\",\"icon\":\"info\",\"details\":\"开源产品合集，包括 Elasticsearch、Kibana、Logstash 以及 Beats 等\",\"link\":\"/statuspage/\"},{\"title\":\"Nginx\",\"icon\":\"sitemap\",\"details\":\"Nginx是一款轻量级的Web 服务器/反向代理服务器及电子邮件（IMAP/POP3）代理服务器。\",\"link\":\"/statuspage/\"},{\"title\":\"Haproxy\",\"icon\":\"rss\",\"details\":\"一种高效、可靠、免费的高可用及负载均衡软件。\",\"link\":\"/statuspage/\"},{\"title\":\"Tomcat\",\"icon\":\"contrast\",\"details\":\"Apache 旗下的一个免费开源的轻量级Web 应用服务。\",\"link\":\"/statuspage/\"},{\"title\":\"Mysql\",\"icon\":\"copy\",\"details\":\"Oracle 旗下最流行的关系型数据库。\",\"link\":\"/statuspage/\"},{\"title\":\"Prometheus\",\"icon\":\"config\",\"details\":\"一个开源的服务监控系统。\",\"link\":\"/statuspage/\"},{\"title\":\"Linux 基础\",\"icon\":\"pic\",\"details\":\"该模块主要介绍一些关于 Linux 运维过程中的问题。\",\"link\":\"/statuspage/\"}],\"copyright\":false,\"footer\":\"<a href=\\\"http://beian.miit.gov.cn/\\\" target=\\\"_blank\\\">京ICP备19033045号-1 </a> |  Copyright © 2023 Ryan's Notebook\",\"description\":\"\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Ryan's Notebook\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"濼鑫的知识库\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2023-02-24T08:36:50.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2023-02-24T08:36:50.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"濼鑫的知识库\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":1.23,\"words\":370},\"filePathRelative\":\"README.md\",\"autoDesc\":true,\"git\":{\"createdTime\":1677227810000,\"updatedTime\":1677227810000,\"contributors\":[{\"name\":\"Ryanxin\",\"email\":\"ryanxin@xx9z@outlook.com\",\"commits\":1}]},\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
