export const pagesRoutes = [
  ["v-6b98b972","/README%20-%20%E5%89%AF%E6%9C%AC.html",{"y":"h","t":"Ryan的知识库","i":"home"},["/README - 副本.html","/README%20-%20%E5%89%AF%E6%9C%AC","/README - 副本.md","/README%20-%20%E5%89%AF%E6%9C%AC.md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"濼鑫的知识库","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-74bc627b","/about/",{"y":"a","t":"关于"},["/about/index.html","/about/README.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"Guide","i":"creative"},["/guide/index.html","/guide/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"Disabling layout and features","i":"config","O":3},["/demo/disable","/demo/disable.md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},["/demo/encrypt","/demo/encrypt.md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown Enhance","i":"markdown","O":2},["/demo/markdown","/demo/markdown.md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"Page Config","i":"page","O":1},["/demo/page","/demo/page.md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"Features Demo","i":"discover","I":0},["/demo/index.html","/demo/README.md"]],
  ["v-74485282","/k8s/",{"y":"a","t":"知识点","i":"creative"},["/k8s/index.html","/k8s/README.md"]],
  ["v-03082396","/statuspage/",{"y":"a","t":"updating","i":"config","O":3},["/statuspage/index.html","/statuspage/README.md"]],
  ["v-2d0ad528","/zh/",{"y":"h","t":"项目主页","i":"home"},["/zh/index.html","/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"y":"s","t":"幻灯片页","i":"slides"},["/zh/slides","/zh/slides.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","t":"Baz","i":"info"},["/guide/bar/baz","/guide/bar/baz.md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"Bar feature","i":"creative"},["/guide/bar/index.html","/guide/bar/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","t":"Ray","i":"config"},["/guide/foo/ray","/guide/foo/ray.md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","t":"Foo feature","i":"config"},["/guide/foo/index.html","/guide/foo/README.md"]],
  ["v-55c04c62","/k8s/log/kubernetes-1.html",{"y":"a","t":"kubernetes 二进制部署"},["/k8s/log/kubernetes-1","/k8s/log/kubernetes-1.md"]],
  ["v-627c4440","/k8s/log/kubernetes-10.html",{"y":"a","t":""},["/k8s/log/kubernetes-10","/k8s/log/kubernetes-10.md"]],
  ["v-64311cdf","/k8s/log/kubernetes-11.html",{"y":"a","t":""},["/k8s/log/kubernetes-11","/k8s/log/kubernetes-11.md"]],
  ["v-65e5f57e","/k8s/log/kubernetes-12.html",{"y":"a","t":""},["/k8s/log/kubernetes-12","/k8s/log/kubernetes-12.md"]],
  ["v-57752501","/k8s/log/kubernetes-2.html",{"y":"a","t":""},["/k8s/log/kubernetes-2","/k8s/log/kubernetes-2.md"]],
  ["v-5929fda0","/k8s/log/kubernetes-3.html",{"y":"a","t":""},["/k8s/log/kubernetes-3","/k8s/log/kubernetes-3.md"]],
  ["v-5aded63f","/k8s/log/kubernetes-4.html",{"y":"a","t":""},["/k8s/log/kubernetes-4","/k8s/log/kubernetes-4.md"]],
  ["v-5c93aede","/k8s/log/kubernetes-5.html",{"y":"a","t":""},["/k8s/log/kubernetes-5","/k8s/log/kubernetes-5.md"]],
  ["v-5e48877d","/k8s/log/kubernetes-6.html",{"y":"a","t":""},["/k8s/log/kubernetes-6","/k8s/log/kubernetes-6.md"]],
  ["v-5ffd601c","/k8s/log/kubernetes-7.html",{"y":"a","t":""},["/k8s/log/kubernetes-7","/k8s/log/kubernetes-7.md"]],
  ["v-61b238bb","/k8s/log/kubernetes-8.html",{"y":"a","t":""},["/k8s/log/kubernetes-8","/k8s/log/kubernetes-8.md"]],
  ["v-6367115a","/k8s/log/kubernetes-9.html",{"y":"a","t":""},["/k8s/log/kubernetes-9","/k8s/log/kubernetes-9.md"]],
  ["v-c9abf226","/k8s/log/",{"y":"a","t":"K8S 训练营","i":"creative"},["/k8s/log/index.html","/k8s/log/README.md"]],
  ["v-c1942916","/zh/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"config","O":3},["/zh/demo/disable","/zh/demo/disable.md"]],
  ["v-65c00218","/zh/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},["/zh/demo/encrypt","/zh/demo/encrypt.md"]],
  ["v-36295574","/zh/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"markdown","O":2},["/zh/demo/markdown","/zh/demo/markdown.md"]],
  ["v-62ced1a6","/zh/demo/page.html",{"y":"a","t":"页面配置","i":"page","O":1},["/zh/demo/page","/zh/demo/page.md"]],
  ["v-2b64e284","/zh/demo/",{"y":"a","t":"主要功能与配置演示","i":"discover","I":0},["/zh/demo/index.html","/zh/demo/README.md"]],
  ["v-47357bdb","/zh/guide/",{"y":"a","t":"指南","i":"creative"},["/zh/guide/index.html","/zh/guide/README.md"]],
  ["v-1e317375","/zh/guide/bar/baz.html",{"y":"a","t":"Baz","i":"info"},["/zh/guide/bar/baz","/zh/guide/bar/baz.md"]],
  ["v-763c1cd7","/zh/guide/bar/",{"y":"a","t":"Bar 功能","i":"creative"},["/zh/guide/bar/index.html","/zh/guide/bar/README.md"]],
  ["v-00fb7173","/zh/guide/foo/ray.html",{"y":"a","t":"Ray","i":"config"},["/zh/guide/foo/ray","/zh/guide/foo/ray.md"]],
  ["v-763e2284","/zh/guide/foo/",{"y":"a","t":"Foo 功能","i":"config"},["/zh/guide/foo/index.html","/zh/guide/foo/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
]
