export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"濼鑫的知识库","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-74bc627b","/about/",{"y":"a","t":"关于"},["/about/index.html","/about/README.md"]],
  ["v-74485282","/k8s/",{"y":"a","t":"知识点","i":"creative"},["/k8s/index.html","/k8s/README.md"]],
  ["v-b8d923aa","/xj/git.html",{"y":"a","t":"Git常用命令与常见问题"},["/xj/git","/xj/git.md"]],
  ["v-2d0acde4","/xj/",{"y":"a","t":"小记","i":"exercise","O":3},["/xj/index.html","/xj/README.md"]],
  ["v-2d0acf77","/xw/",{"y":"a","t":"知识点","i":"creative"},["/xw/index.html","/xw/README.md"]],
  ["v-03082396","/statuspage/",{"y":"a","t":"updating","i":"config","O":3},["/statuspage/index.html","/statuspage/README.md"]],
  ["v-55c04c62","/k8s/log/kubernetes-1.html",{"y":"a","t":"1.kubernetes 二进制部署"},["/k8s/log/kubernetes-1","/k8s/log/kubernetes-1.md"]],
  ["v-627c4440","/k8s/log/kubernetes-10.html",{"y":"a","t":"10.实战案例-WordPress"},["/k8s/log/kubernetes-10","/k8s/log/kubernetes-10.md"]],
  ["v-64311cdf","/k8s/log/kubernetes-11.html",{"y":"a","t":"11.实战案例-基于zookeeper实现微服务动态注册和发现"},["/k8s/log/kubernetes-11","/k8s/log/kubernetes-11.md"]],
  ["v-65e5f57e","/k8s/log/kubernetes-12.html",{"y":"a","t":"12.ingress 实现基于域名的多虚拟主机,URL转发及多域名HTTPS实现案例"},["/k8s/log/kubernetes-12","/k8s/log/kubernetes-12.md"]],
  ["v-679ace1d","/k8s/log/kubernetes-13.html",{"y":"a","t":"13.HPA自动伸缩pod数量"},["/k8s/log/kubernetes-13","/k8s/log/kubernetes-13.md"]],
  ["v-694fa6bc","/k8s/log/kubernetes-14.html",{"y":"a","t":"14.K8S 持续集成与部署"},["/k8s/log/kubernetes-14","/k8s/log/kubernetes-14.md"]],
  ["v-57752501","/k8s/log/kubernetes-2.html",{"y":"a","t":"2.etcd 客户端使用、数据备份与恢复"},["/k8s/log/kubernetes-2","/k8s/log/kubernetes-2.md"]],
  ["v-5929fda0","/k8s/log/kubernetes-3.html",{"y":"a","t":"3. yaml文件语法基础"},["/k8s/log/kubernetes-3","/k8s/log/kubernetes-3.md"]],
  ["v-5aded63f","/k8s/log/kubernetes-4.html",{"y":"a","t":"4.kubernetesAPI资源对象"},["/k8s/log/kubernetes-4","/k8s/log/kubernetes-4.md"]],
  ["v-5c93aede","/k8s/log/kubernetes-5.html",{"y":"a","t":"5.k8s实战案例-nginx与tomcat实现动静分离"},["/k8s/log/kubernetes-5","/k8s/log/kubernetes-5.md"]],
  ["v-5e48877d","/k8s/log/kubernetes-6.html",{"y":"a","t":"6.k8s使用ceph实现数据持久化"},["/k8s/log/kubernetes-6","/k8s/log/kubernetes-6.md"]],
  ["v-5ffd601c","/k8s/log/kubernetes-7.html",{"y":"a","t":"7.Pod的状态和探针"},["/k8s/log/kubernetes-7","/k8s/log/kubernetes-7.md"]],
  ["v-61b238bb","/k8s/log/kubernetes-8.html",{"y":"a","t":"8.实战案例-基于StatefulSetMySQL主从架构"},["/k8s/log/kubernetes-8","/k8s/log/kubernetes-8.md"]],
  ["v-6367115a","/k8s/log/kubernetes-9.html",{"y":"a","t":"9.实战案例-运行java应用"},["/k8s/log/kubernetes-9","/k8s/log/kubernetes-9.md"]],
  ["v-c9abf226","/k8s/log/",{"y":"a","t":"K8S 训练营","i":"creative"},["/k8s/log/index.html","/k8s/log/README.md"]],
  ["v-19eb9422","/xj/xx/qiniu.html",{"y":"a","t":""},["/xj/xx/qiniu","/xj/xx/qiniu.md"]],
  ["v-c760ee6a","/xj/xx/",{"y":"a","t":"目录","i":"config","O":3},["/xj/xx/index.html","/xj/xx/README.md"]],
  ["v-3fd481c8","/xj/xx/rmxc.html",{"y":"a","t":""},["/xj/xx/rmxc","/xj/xx/rmxc.md"]],
  ["v-0a9e18b8","/xj/xx/tabby.html",{"y":"a","t":"updating","i":"config","O":3},["/xj/xx/tabby","/xj/xx/tabby.md"]],
  ["v-f8c93f34","/xw/hyy/1.html",{"y":"a","t":"汉译英技巧课1"},["/xw/hyy/1","/xw/hyy/1.md"]],
  ["v-f55f8df6","/xw/hyy/2.html",{"y":"a","t":"汉译英技巧课2"},["/xw/hyy/2","/xw/hyy/2.md"]],
  ["v-03c9579e","/xw/hyy/",{"y":"a","t":"C汉译英技巧课","i":"miao"},["/xw/hyy/index.html","/xw/hyy/README.md"]],
  ["v-78c9e09f","/xw/wx/1.html",{"y":"a","t":"完型技巧课1"},["/xw/wx/1","/xw/wx/1.md"]],
  ["v-7a7eb93e","/xw/wx/2.html",{"y":"a","t":"完型技巧课2"},["/xw/wx/2","/xw/wx/2.md"]],
  ["v-c5f292d2","/xw/wx/",{"y":"a","t":"F完型填空","i":"miao"},["/xw/wx/index.html","/xw/wx/README.md"]],
  ["v-3683e551","/xw/tc/1.html",{"y":"a","t":"挑错技巧课1"},["/xw/tc/1","/xw/tc/1.md"]],
  ["v-3838bdf0","/xw/tc/2.html",{"y":"a","t":"挑错技巧课2"},["/xw/tc/2","/xw/tc/2.md"]],
  ["v-c5f2ae6e","/xw/tc/",{"y":"a","t":"D挑错","i":"miao"},["/xw/tc/index.html","/xw/tc/README.md"]],
  ["v-537d96f3","/xw/yf/1.html",{"y":"a","t":"词汇与结构1"},["/xw/yf/1","/xw/yf/1.md"]],
  ["v-55326f92","/xw/yf/2.html",{"y":"a","t":"词汇与结构2"},["/xw/yf/2","/xw/yf/2.md"]],
  ["v-c5f2882a","/xw/yf/",{"y":"a","t":"B词汇与结构","i":"miao"},["/xw/yf/index.html","/xw/yf/README.md"]],
  ["v-f8898596","/xw/yd/1.html",{"y":"a","t":"阅读理解技巧课1"},["/xw/yd/1","/xw/yd/1.md"]],
  ["v-f51fd458","/xw/yd/2.html",{"y":"a","t":"阅读理解技巧课2"},["/xw/yd/2","/xw/yd/2.md"]],
  ["v-c5f288a6","/xw/yd/",{"y":"a","t":"A阅读理解","i":"miao"},["/xw/yd/index.html","/xw/yd/README.md"]],
  ["v-52f02eb4","/xw/yyh/1.html",{"y":"a","t":"英译汉技巧课1"},["/xw/yyh/1","/xw/yyh/1.md"]],
  ["v-4f867d76","/xw/yyh/2.html",{"y":"a","t":"英译汉技巧课2"},["/xw/yyh/2","/xw/yyh/2.md"]],
  ["v-03d10fde","/xw/yyh/",{"y":"a","t":"E英译汉","i":"miao"},["/xw/yyh/index.html","/xw/yyh/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
]
